<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Webczat.DotnetObjectBrowser.Lsp</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.ExternalAccess.Extensions"/>
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common"/>
  </ItemGroup>
</Project>
